# Generated by Django 4.2.8 on 2024-01-05 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('traceSum', models.JSONField()),
                ('cpuutil', models.IntegerField()),
                ('color', models.CharField(default='0000000', max_length=100)),
            ],
        ),
    ]
