# Generated by Django 4.2.8 on 2024-01-08 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpuprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traces',
            name='cpuutil',
        ),
        migrations.AddField(
            model_name='traces',
            name='finished_capture',
            field=models.BooleanField(default=False),
        ),
    ]
