# Generated by Django 4.2.8 on 2026-09-23 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpuprofile', '0003_capturestatus_remove_traces_finished_capture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('port', models.PositiveIntegerField()),
                ('db', models.PositiveIntegerField()),
                ('username', models.CharField(blank=True, max_length=255)),
                ('amount', models.PositiveIntegerField()),
                ('interval', models.FloatField()),
                ('samples_requested', models.PositiveIntegerField()),
                ('max_sample_seconds', models.FloatField()),
                ('warn_usec', models.FloatField()),
                ('crit_usec', models.FloatField()),
                ('slowlog_threshold_us', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('running', 'running'), ('done', 'done'), ('stopped', 'stopped'), ('failed', 'failed'), ('interrupted', 'interrupted')], default='running', max_length=20)),
                ('stop_requested', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('stats', models.JSONField()),
                ('avg_usec_per_call', models.FloatField(null=True)),
                ('cpu_pct', models.FloatField(null=True)),
                ('ops_per_sec', models.FloatField(null=True)),
                ('level', models.CharField(max_length=10)),
                ('capture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='cpuprofile.capture')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.DeleteModel(
            name='CaptureStatus',
        ),
        migrations.DeleteModel(
            name='Traces',
        ),
    ]
